version: "2"
run:
  go: "1.20"
linters:
  enable:
    # Default linters, which we make explicit.
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

    # Optional linters, which we choose to apply additionally.
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - dupl
    - errname
    - errorlint
    - funlen
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - godot
    - gosec
    - lll
    - misspell
    - nestif
    - noctx
    - prealloc
    - reassign
    - revive
    - thelper
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign
    - whitespace
    - wsl_v5
  settings:
    revive:
      rules:
        - name: exported
    wsl_v5:
#      allow-first-in-block: true
#      allow-whole-block: false
#      branch-max-lines: 2
  exclusions:
    generated: lax
    presets:
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - lll
        source: '^// '
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
  settings:
    gci:
      sections:
        - standard
        - prefix(github.com/e-identification/bankid-go)
        - default
      custom-order: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
